### ISSUE TITLE
Currently doesn't run the tasks on initial run

### ISSUE THREAD

**Issue by tjbenton** [flyjs/fly-watch#1]
When this was apart of the fly lib it used to run the tasks that you would pass into the watch function 1 time while it started to watch for changes. This way you didn't have to run `fly.start('taskname')` along with every `fly.watch` instance.

**Comment by lukeed** [comment]
Yessir! This was changed in [`v1.1.0`](https://github.com/flyjs/fly-watch/releases/tag/v1.1.0). I found that more often than not, I just wanted to start a watcher. And in the events that a "pre-build" was needed, it was (and is) very easy to do so:

```js
exports.default = function * (fly) {
  yield fly.start('build').watch('src/**/*.js', 'scripts');
}

// or

exports.default = function * (fly) {
  yield fly.parallel(['foo', 'bar', 'baz']).start('watch');
}
```

Another [example](https://github.com/zeit/next.js/blob/master/flyfile.js#L46-L53) from the wild. Not too bad at all, imo. 😄 

Plus, it's not always the case that the way your `watch`ers handle globs is _actually_ the way you want to set up a first build. In fact, it's usually not! Then you have to run other "setup tasks" anyway.

(Closing as it's intentional behavior.)
